### ISSUE TITLE
      throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails);

### ISSUE THREAD

**Issue by Rajdeep-4321** [AmitJoki/Enigma#10]
getting error "      throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
"

when implementing the code into my app.

**Comment by Rajdeep-4321** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/39374574/70622572-36bd0d00-1c42-11ea-8bf0-3169cb791922.png)

**Comment by AmitJoki** [comment]
The image shows that the error is occuring outside of the files of Enigma.

**Comment by Rajdeep-4321** [comment]
No,
i also run your whole code but it gave same error

**Comment by AmitJoki** [comment]
It seems your mobile doesn't support fingerprints. I am going to close this unless you can come up with a detailed error message than the one you've now.
