### ISSUE TITLE
Not past login screen

### ISSUE THREAD

**Issue by jessejay247** [AmitJoki/Enigma#11]
Hello amit, the file built but not getting past login screen . loads and loads for ever

**Comment by jessejay247** [comment]
didnt set up security rules, my bad

**Comment by AmitJoki** [comment]
@jessejay247 happens :)

**Comment by kaushik1710** [comment]
> didnt set up security rules, my bad

I have even set the rules in storage and firestore still cannot pass login page can you please help !!₹
