### ISSUE TITLE
Notification is not working

### ISSUE THREAD

**Issue by UnluckyY1** [AmitJoki/Enigma#12]
Hey iam nooby with firebase i setup evrey think right and the app is runing the only thing that is not working is the notification can u please explain how does it work ?
Thank you

**Comment by AmitJoki** [comment]
You need to upload the cloud functions using`firebase deploy --only functions`

**Comment by UnluckyY1** [comment]
Thank you for your response is there any guide for that ? like i said am nooby with firebase

**Comment by UnluckyY1** [comment]
after some research i found out how to do it but i get this error
>firebase deploy --only functions

Error: Authorization failed. This account is missing the following required permissions on project amitjoki-enigma:

  cloudfunctions.functions.create
  cloudfunctions.functions.delete
  cloudfunctions.functions.get
  cloudfunctions.functions.list
  cloudfunctions.functions.update
  cloudfunctions.operations.get
  firebase.projects.get

**Comment by UnluckyY1** [comment]
fixed the last error but i get a new one now 
even when i try npm run build  inside the function folder i got error i hope that u can awnser as soon as possible my school project depends on it next week thank you
functions@ lint C:\SRC\Chat-master\functions
> eslint .

'eslint' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\siyou\AppData\Roaming\npm-cache\_logs\2020-02-18T18_48_11_704Z-debug.log
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix "%RESOURCE_DIR%" run lint ENOENT
    at notFoundError (C:\Users\siyou \AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\siyou\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\mobile\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

Error: functions predeploy error: Command terminated with non-zero exit code1

C:\SRC\Chat-master>cd functions

C:\SRC\Chat-master\functions>npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\siyou\AppData\Roaming\npm-cache\_logs\2020-02-18T18_52_57_004Z-debug.log

**Comment by AmitJoki** [comment]
I am guessing it has to do with how eslint is installed or configured in your system? 

Also, you should create your own firebase project and have its JSON put in here.

**Comment by UnluckyY1** [comment]
Thank you for ur quick response i will do more research tomorrow and configure eslint and update you with the news

**Comment by jessejay247** [comment]
app does not open on notification click
