### ISSUE TITLE
many errors please update

### ISSUE THREAD

**Issue by kaushik1710** [AmitJoki/Enigma#16]
![Screenshot 2020-04-13 at 6 26 12 PM](https://user-images.githubusercontent.com/45241376/79122020-52811d00-7db4-11ea-82e2-acff0044b485.png)

**Comment by kaushik1710** [comment]
ive performed pod repo update also could you please check on this

**Comment by AmitJoki** [comment]
I cannot help with iOS specific problems as I don't own a device. I am afraid you're going to have to debug this out on your own.
