### ISSUE TITLE
cache network image provider 

### ISSUE THREAD

**Issue by kaushik1710** [AmitJoki/Enigma#17]
having a version problem even after changing the version in pubsepc.yaml I'm getting the error

Because Enigma depends on cached_network_image ^2.1.0+1 which depends on flutter_cache_manager ^1.2.0, flutter_cache_manager ^1.2.0 is required.
So, because Enigma depends on flutter_cache_manager ^0.3.2, version solving failed.

**Comment by AmitJoki** [comment]
The error is pretty clear. You need to upgrde the flutter_cache_manager to ^1.2.0 and then upgrade the cahced_network_image ^2.1.0+1
