### ISSUE TITLE
Activate Notifications

### ISSUE THREAD

**Issue by southernsons** [AmitJoki/Enigma#4]
Hi,
thank you for the effort developing this app. So currently I am playing around with it to learn Flutter/Dart.
I wanted to find out how to activate push notifications and also for some reason I cannot upload pictures. When I ant to add a profile pic for example I do not have the "right" to add them. When I open the camera and add a picture which I just took the app seems to load for ever. I then need to close the app but cannot add a picture.

**Comment by AmitJoki** [comment]
I have included a starting point for notifications as a Firebase Cloud Messaging Function and it can be found in the `functions` folder.

As for your other issue, without much details, it seems to me that you've not given the permission for the app to access those.

Try going to settings -> apps -> Enigma -> permissions and enable the suitable permissions and see if that helps.

**Comment by southernsons** [comment]
Hi there,
I will relook at the Firebase CM function.

Regarding the image issue: I cannot grant access to my Photos as the function doe snot exist in my app. When I check the settings I can grant permissions to location, microphone etc but Photos does not exist.

I connected my iPhone to my Mac and installed the app there. At some stage I got the following errors:

```
flutter: Caught error: NoSuchMethodError: The getter 'images' was called on null.
Receiver: null
Tried calling: images
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _ChatScreenState.buildInput.<anonymous closure> (package:GBWA/chat.dart:647:35)
<asynchronous suspension>
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#13     _rootRunUnary (dart:async/zone.dart:1136:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#16     _invoke1 (dart:ui/hooks.dart:250:10)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
Application finished.
```

I am currently updating my Flutter Branch Master so let's hope this will resolve the issue.

**Comment by AmitJoki** [comment]
Ah! I don't have an iPhone so this is entirely untested on iOS. But I won't be able to patch this up too as I don't have the device. The fix would be to change the dart code so it makes use of Apple's way of getting photos and whatever permissions that are required.

If you're interested in it, may be you can patch it up and submit a pull request and I'll review it and merge it so others could benefit from it too.

**Comment by kaushik1710** [comment]
> Hi there,
> I will relook at the Firebase CM function.
> 
> Regarding the image issue: I cannot grant access to my Photos as the function doe snot exist in my app. When I check the settings I can grant permissions to location, microphone etc but Photos does not exist.
> 
> I connected my iPhone to my Mac and installed the app there. At some stage I got the following errors:
> 
> ```
> flutter: Caught error: NoSuchMethodError: The getter 'images' was called on null.
> Receiver: null
> Tried calling: images
> flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
> #1      _ChatScreenState.buildInput.<anonymous closure> (package:Enigma/chat.dart:647:35)
> <asynchronous suspension>
> #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
> #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
> #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
> #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
> #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
> #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> #13     _rootRunUnary (dart:async/zone.dart:1136:13)
> #14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> #16     _invoke1 (dart:ui/hooks.dart:250:10)
> #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
> Application finished.
> ```
> 
> I am currently updating my Flutter Branch Master so let's hope this will resolve the issue.

I can help u with this
