### ISSUE TITLE
Messages lost after uninstall/install

### ISSUE THREAD

**Issue by postacik** [AmitJoki/Enigma#7]
Hi,
Since encryption related info is stored in the application data, after uninstall and then reinstall + register with the same phone number, all previous messages before uninstall appear empty.

Since WhatsApp stores the messages locally and gives an option to back them up on Google drive, you never loose old messages after a reinstall.

Do you have any suggestions to overcome this problem in your app?

**Comment by AmitJoki** [comment]
The fix is to store the messages locally and load them up without encryption/decryption. That would also mean adding a field to see if a message is plain or encrypted.

That would also mean a significant change in the way Enigma is currently structured for its functionality.

**Comment by postacik** [comment]
Telegram also stores messages in the cloud. Does it have the same problem?
