### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by postacik** [AmitJoki/Enigma#8]
Can you explain a bit about the details of end to end encryption used in this app?

**Comment by AmitJoki** [comment]
it is shared encryption. The private keys are stored in the device and the public keys are well public. The messages are encrypted before sending by the shared key and decrypted at the receiver with the shared key.

With the shared key itself only being generated on either of the devices using the private key stored in the respective devices.

**Comment by postacik** [comment]
So I have to read the public key of a user from the users collection before sending a message to that user. Is that right?
