### ISSUE TITLE
Build Apk error

### ISSUE THREAD

**Issue by lordmen99** [AmitJoki/Enigma#9]
Hi, i get error when try build apk

`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

ERROR: [TAG] Failed to resolve variable '${junit.version}'

ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'

Compiler message:

../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.8.0/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../Downloads/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').

  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/admin/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 776

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/admin/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by AmitJoki** [comment]
Look at this issue: https://github.com/renefloor/flutter_cached_network_image, basically you need to upgrade `cache_network_image_provider` package to `2.0.0-rc` in `pubspec.yml`

**Comment by lordmen99** [comment]
i have do that but still not success build apk and debug to emulator

**Comment by AmitJoki** [comment]
If you'd done that, that error would have been gone and you would have additional error statements. 

Do a `flutter upgrade`, use the correct version of `cache_network_image_provider` and it should run. Else, report the error you're getting.

**Comment by lordmen99** [comment]
i use visual studio code

**Comment by AmitJoki** [comment]
https://flutter.dev/docs/development/tools/vs-code
